// Copyright Kyle Cuss and Cuss Programming 2026.

#pragma once

#include "NativeGameplayTags.h"

namespace ARPGGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_CombatTargetChanged);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_CombatRoleChanged);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_CombatGoalChanged);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_AttackOpportunity);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_SupportOpportunity);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_RangedPotshot);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_CompanionOwnerChanged);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_CompanionFollowRequired);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_CompanionFollowSatisfied);
}